services:
  - type: web
    name: instituto-embalagens
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
    startCommand: |
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: instituto-embalagens
          property: host
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: instituto-embalagens-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: instituto-embalagens-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: instituto-embalagens-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: instituto-embalagens-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: instituto-embalagens-db
          property: password
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database

databases:
  - name: instituto-embalagens-db
    databaseName: instituto_embalagens
    user: instituto_user

